### ISSUE TITLE
Node.js 0.11.15 `compress: true` error

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/grunt-contrib-uglify#287]
```
Running "uglify:minify" (uglify) task
[TypeError: Cannot assign to read only property 'warnings' of true]
>> Uglifying source dist/htmlminifier.js failed.
Warning: Uglification failed.
Cannot assign to read only property 'warnings' of true.
 Use --force to continue.
```

```js
uglify: {
  options: {
    banner: '<%= banner %>',
    compress: true,
    mangle: true,
    preserveComments: false,
    report: 'min'
  },
  minify: {
    files: {
      'dist/htmlminifier.min.js': '<%= concat.dist.dest %>'
    }
  }
}
```

If I comment out `compress: true` or change it to `compress: { drop_console: true }` everything goes well.

This only happens with Node.js 0.11.15 regardless of OS: https://travis-ci.org/kangax/html-minifier/jobs/47934702

**Comment by KrisSiegel** [comment]
Also running into this issue but haven't had a chance to track down its source.

**Comment by XhmikosR** [comment]
I feel like it's a bug in node but haven't had the chance to look into it
closer either.

**Comment by robertdunaway** [comment]
I installed NodeJS on a new machine and I now have this problem on the new machine but not the old machine.  For me it only happen with ngannotate.  Concat and Uglify work.

**Comment by XhmikosR** [comment]
BTW I see it with 0.11.16 too.

**Comment by bricss** [comment]
Getting this error in Node 0.12

**Comment by bricss** [comment]
Problem was solved by adding 'compress : { warnings: false }'

**Comment by XhmikosR** [comment]
Or you can just remove it completely because your way will silence the warnings.

**Comment by travischoma** [comment]
Any more ideas on this one besides disabling compress? Had to disable it in io 1.1.0

**Comment by braoru** [comment]
Same bug on 0.12.0 for me

**Comment by giannisp** [comment]
`options: { compress: {} }` seems to be working for me with 0.12.0.

**Comment by tremby** [comment]
Please clarify: is `compress: true` not allowed any more? Should I use `compress: {}` instead to mean the same thing (compress with whatever the default options are)?

**Comment by bricss** [comment]
Everything works as is, just update to latest version. Bug was resolved.

**Comment by tremby** [comment]
D'oh -- you're right. I had somehow updated to 0.7.0 (where the bug remained) rather than 0.8.0.
